### PR TITLE
Adding a test case for incorrect close frame payload size 1 byte

### PR DESCRIPTION
**Pull request by jitsni**

### CODE REVIEW

**Comment by dpwspoon** [comment]
Should we have a mirror test for close coming from other direction (server initiating close)?

**Comment by jfallows** [comment]
Yes, two scenarios needed, one for client initiated and one for server
initiated.

John

Btw, I interpret this test case to mean that an empty close frame is okay,
and a close frame with an error code (2 bytes) is okay. But a close with
half an error code (1 byte) is *not* okay, right? And the appropriate
response is a close with "invalid protocol" code.

John

On Tuesday, January 13, 2015, David Witherspoon <notifications@github.com>
wrote:

> Should we have a mirror test for close coming from other direction (server
> initiating close)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/k3po/specification.ws/pull/22#issuecomment-69834761>.
>


-- 

*John Fallows*
CTO*  |  *Phone: +1.650.960.8148  |  Mobile: +1.415.215.6597
*----------------------------------------------------------------------*
KAAZING >|<
Event-Driven Communication. Fast. Secure. Mobile. Guaranteed.
Kaazing.com <http://www.kaazing.com/>  |  Download
<http://kaazing.com/download.html>  |  Blog <http://blog.kaazing.com/>  |
Twitter <https://twitter.com/kaazing>

**Comment by jitsni** [comment]
Yes, we need to have one for server side.

On Tue, Jan 13, 2015 at 2:35 PM, David Witherspoon <notifications@github.com

**Comment by jitsni** [comment]
Yes, these are the valid scenarios
close frame can have payload = 0 bytes (no close code)
close frame can have payload = 2 bytes (close code, but no close reason)
close frame can have payload = 3 - 125 bytes (close code + close reason)

I see that some servers  1. just close the tcp connection 2. send the
invalid protocol code(or some other one) 3. send the invalid protocol
code+reason

we have a test script (sendCloseFrameWithPayloadLength1.rpt)  wsn transport

**Pull request merged**
